const { contextBridge, ipcRenderer } = require("electron");
function on(channel,handler){const listener=(_event,value)=>handler(value);ipcRenderer.on(channel,listener);return()=>ipcRenderer.removeListener(channel,listener);}
contextBridge.exposeInMainWorld("men",{
  snapshot:()=>ipcRenderer.invoke("men:snapshot"),startService:name=>ipcRenderer.invoke("men:start-service",name),stopService:name=>ipcRenderer.invoke("men:stop-service",name),restartService:name=>ipcRenderer.invoke("men:restart-service",name),startAll:()=>ipcRenderer.invoke("men:start-all"),stopAll:()=>ipcRenderer.invoke("men:stop-all"),setProfile:profile=>ipcRenderer.invoke("men:set-profile",profile),
  getLogs:service=>ipcRenderer.invoke("men:get-logs",service),getConfig:()=>ipcRenderer.invoke("men:get-config"),saveConfig:config=>ipcRenderer.invoke("men:save-config",config),diagnostics:()=>ipcRenderer.invoke("men:diagnostics"),repairEnvironment:()=>ipcRenderer.invoke("men:repair-environment"),
  health:()=>ipcRenderer.invoke("men:health"),healthRepair:action=>ipcRenderer.invoke("men:health-repair",action),roadmap:()=>ipcRenderer.invoke("men:roadmap"),projectOverview:()=>ipcRenderer.invoke("men:project-overview"),taskSnapshot:()=>ipcRenderer.invoke("men:task-snapshot"),runTask:kind=>ipcRenderer.invoke("men:run-task",kind),quality:()=>ipcRenderer.invoke("men:quality"),
  databaseCenter:()=>ipcRenderer.invoke("men:database-center"),databaseBackup:()=>ipcRenderer.invoke("men:database-backup"),databaseRestore:file=>ipcRenderer.invoke("men:database-restore",file),databaseDeleteBackup:file=>ipcRenderer.invoke("men:database-delete-backup",file),resetDatabase:token=>ipcRenderer.invoke("men:reset-database",token),
  git:()=>ipcRenderer.invoke("men:git"),gitFetch:()=>ipcRenderer.invoke("men:git-fetch"),gitPull:()=>ipcRenderer.invoke("men:git-pull"),storage:()=>ipcRenderer.invoke("men:storage"),storageClean:key=>ipcRenderer.invoke("men:storage-clean",key),journal:()=>ipcRenderer.invoke("men:journal"),assistant:()=>ipcRenderer.invoke("men:assistant"),
  sessionStart:()=>ipcRenderer.invoke("men:session-start"),sessionStop:()=>ipcRenderer.invoke("men:session-stop"),sessionSnapshot:()=>ipcRenderer.invoke("men:session-snapshot"),
  updateSnapshot:()=>ipcRenderer.invoke("men:update-snapshot"),updateCheck:()=>ipcRenderer.invoke("men:update-check"),updateDownload:()=>ipcRenderer.invoke("men:update-download"),updateInstall:()=>ipcRenderer.invoke("men:update-install"),
  clearHistory:()=>ipcRenderer.invoke("men:clear-history"),openApplication:()=>ipcRenderer.invoke("men:open-application"),openBackend:()=>ipcRenderer.invoke("men:open-backend"),openSwagger:()=>ipcRenderer.invoke("men:open-swagger"),openPgadmin:()=>ipcRenderer.invoke("men:open-pgadmin"),openWorkspace:()=>ipcRenderer.invoke("men:open-workspace"),openRoadmapFile:()=>ipcRenderer.invoke("men:open-roadmap-file"),openLogDirectory:()=>ipcRenderer.invoke("men:open-log-directory"),openGitHub:()=>ipcRenderer.invoke("men:open-github"),openBackupDir:()=>ipcRenderer.invoke("men:open-backup-dir"),
  onState:handler=>on("men:state",handler),onLog:handler=>on("men:log",handler),onTask:handler=>on("men:task",handler),onUpdate:handler=>on("men:update",handler),onSession:handler=>on("men:session",handler)
});
