const state={config:null,snapshot:null,health:null,roadmap:null,tasks:{running:[],lastResults:{},history:[]},session:{active:null,sessions:[]},update:null,git:null,database:null,storage:null,journal:null,assistant:null,diagnostics:null,logs:{all:[],docker:[],postgres:[],backend:[],frontend:[],tasks:[],database:[]},logFilter:"all",operationalLoaded:false};
const labels={docker:"Docker Desktop",postgres:"PostgreSQL",backend:"Spring Boot API",frontend:"Angular Frontend"};
const statusLabels={running:"EN LIGNE",external:"EXTERNE",starting:"DÉMARRAGE",stopping:"ARRÊT",error:"ERREUR",stopped:"ARRÊTÉ",unknown:"INCONNU"};
const roadmapLabels={done:"TERMINÉ",current:"EN COURS",planned:"À VENIR",blocked:"BLOQUÉ"};
const el=id=>document.getElementById(id);const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const fmtTime=iso=>iso?new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(iso)):"—";
const fmtDate=iso=>iso?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(iso)):"—";
function fmtDuration(ms){if(ms==null)return"—";const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),h=Math.floor(m/60);return h?`${h}h ${m%60}m`:m?`${m}m ${s%60}s`:`${s}s`;}
function fmtBytes(v){const n=Number(v||0);if(!n)return"0 Mo";if(n>=1024**3)return`${(n/1024**3).toFixed(2)} Go`;return`${(n/1024**2).toFixed(0)} Mo`;}
function toast(message,type="info"){const n=document.createElement("div");n.className=`toast ${type}`;n.textContent=message;el("toastHost").appendChild(n);setTimeout(()=>n.remove(),4200);}
function busy(button,on,label="En cours..."){if(!button)return;if(!button.dataset.original)button.dataset.original=button.textContent;button.disabled=on;button.textContent=on?label:button.dataset.original;}
const info=(label,value,klass="")=>`<div class="info-item"><div class="info-label">${esc(label)}</div><div class="info-value ${klass}">${esc(value??"—")}</div></div>`;

function renderGate(){const u=state.update;if(!u)return;const gate=el("mandatoryUpdateGate"),percent=Math.max(0,Math.min(100,Number(u.progress?.percent||0)));el("gateCurrentVersion").textContent=`Version installée ${u.currentVersion||"—"}`;el("gateTargetVersion").textContent=u.availableVersion?`Version cible ${u.availableVersion}`:"Version cible —";el("gateProgress").style.width=`${percent}%`;el("gateRetry").style.display=u.status==="error"?"inline-flex":"none";el("gateError").textContent=u.error||"";
  if(u.gate==="open"){gate.classList.add("hidden");return;}gate.classList.remove("hidden");
  const map={checking:["Vérification obligatoire","Recherche de la dernière version..."],available:["Mise à jour obligatoire",`La version ${u.availableVersion||"plus récente"} doit être installée.`],downloading:["Téléchargement de la mise à jour",`${percent.toFixed(0)} %`],downloaded:["Mise à jour prête","Installation automatique imminente..."],installing:["Installation en cours","MEN Pilot Launcher va redémarrer automatiquement."],error:["Contrôle impossible","Le launcher reste verrouillé jusqu'à ce que le contrôle réussisse."],unconfigured:["Canal non configuré","Impossible de vérifier la version."]};const pair=map[u.status]||["Vérification de la version","Initialisation..."];el("gateTitle").textContent=pair[0];el("gateMessage").textContent=pair[1];el("gateProgressText").textContent=u.status==="downloading"?`${percent.toFixed(0)} % téléchargé`:pair[1];}

function renderProfiles(){const s=el("profileSelect"),profiles=state.config?.profiles||{};s.innerHTML=Object.entries(profiles).map(([k,v])=>`<option value="${esc(k)}">${esc(v.label||k.toUpperCase())}</option>`).join("");s.value=state.config?.activeProfile||"dev";}
function renderDashboard(){const snap=state.snapshot;if(!snap?.services)return;const h=state.health,g=state.git,q=state.tasks,r=state.roadmap;el("lastRefresh").textContent=`Dernière actualisation ${fmtTime(snap.at)} · ${String(snap.activeProfile||"dev").toUpperCase()}`;el("workspaceShort").textContent=snap.workspace||"";
  el("metricHealth").textContent=h?({healthy:"SAIN",warning:"ATTENTION",critical:"CRITIQUE"}[h.global]||h.global):"—";el("metricHealthDetail").textContent=h?`${h.summary.healthy}/${h.summary.total} contrôles sains`:"Analyse...";
  el("metricGit").textContent=g?.available?g.branch:"—";el("metricGitDetail").textContent=g?.available?`${g.commit} · ${g.dirty?`${g.changedFiles} modification(s)`:"propre"}`:"Git indisponible";
  const bt=q?.lastResults?.backendTests,ft=q?.lastResults?.frontendTests;el("metricQuality").textContent=`B ${bt?.ok?"✓":bt?"✗":"—"} · F ${ft?.ok?"✓":ft?"✗":"—"}`;
  el("metricRoadmap").textContent=r?.summary?.total?`${r.summary.done||0}/${r.summary.total}`:"—";el("metricRoadmapCurrent").textContent=r?.current?`${r.current.id} · ${r.current.summary}`:"Aucune étape détectée";
  const global=el("globalStatus");global.className=`global-status ${h?.global==="healthy"?"good":h?.global==="critical"?"bad":"warn"}`;global.innerHTML=`<span class="dot"></span><span>${h?.global==="healthy"?"MEN Pilot sain":h?.global==="critical"?"Anomalie critique":"Surveillance requise"}</span>`;
  el("serviceGrid").innerHTML=Object.values(snap.services).map(s=>{const cfg=state.config?.services?.[s.name]||{};return`<article class="service-card"><div class="service-head"><div><div class="service-name">${esc(labels[s.name]||s.name)}</div><div class="service-sub">${esc(cfg.startCommand||"")}</div></div><span class="badge ${esc(s.status)}">${esc(statusLabels[s.status]||s.status)}</span></div><div class="service-details"><div class="detail"><div class="detail-label">PORT</div><div class="detail-value">${esc(cfg.port||"—")}</div></div><div class="detail"><div class="detail-label">PID</div><div class="detail-value">${esc(s.pid||"—")}</div></div><div class="detail"><div class="detail-label">ÉTAT</div><div class="detail-value">${esc(s.portOpen?"Disponible":"Arrêté")}</div></div></div><div class="service-actions"><button class="btn secondary service-action" data-action="start" data-service="${s.name}">Démarrer</button><button class="btn secondary service-action" data-action="restart" data-service="${s.name}" ${s.status==="external"?"disabled":""}>Redémarrer</button><button class="btn danger service-action" data-action="stop" data-service="${s.name}" ${s.status==="external"?"disabled":""}>Arrêter</button></div></article>`;}).join("");renderRecentHistory();renderSession();renderAssistant(true);}
function renderRecentHistory(){const rows=state.snapshot?.history||[];el("recentHistory").innerHTML=rows.slice(0,12).map(x=>`<div class="timeline-item"><span class="timeline-time">${fmtTime(x.at)}</span><span class="timeline-service">${esc(x.service)}</span><span class="timeline-outcome ${esc(x.outcome)}">${esc(x.action)} · ${esc(x.outcome)}</span></div>`).join("")||'<div class="muted">Aucune activité.</div>';}
function renderSession(){const s=state.session?.active;el("sessionToggle").textContent=s?"Terminer session":"Démarrer session";el("sessionPanel").innerHTML=s?`<div class="session-current"><strong>Session active</strong><div class="muted">Depuis ${fmtDate(s.startedAt)} · ${fmtDuration(Date.now()-new Date(s.startedAt).getTime())}</div><div class="muted">${s.roadmap?`${esc(s.roadmap.id)} · ${esc(s.roadmap.summary)}`:"Aucune étape roadmap associée"}</div><div class="muted">Branche ${esc(s.git?.branch||"—")} · ${s.errors||0} erreur(s)</div></div>`:'<div class="muted">Aucune session active.</div>';}

function renderHealth(){const h=state.health;if(!h)return;el("healthHero").innerHTML=`<div class="health-hero ${h.global}"><div><div class="health-state">${h.global==="healthy"?"MEN Pilot est sain":h.global==="critical"?"Intervention requise":"MEN Pilot nécessite une vérification"}</div><div class="muted">${h.summary.healthy} sain(s) · ${h.summary.warning} avertissement(s) · ${h.summary.critical} critique(s)</div></div></div>`;el("healthGrid").innerHTML=h.checks.map(c=>`<article class="health-card ${c.status}"><div class="health-card-head"><strong>${esc(c.label)}</strong><span class="health-pill ${c.status}">${c.status==="healthy"?"OK":c.status==="warning"?"ATTENTION":"ERREUR"}</span></div><div class="health-detail">${esc(c.detail)}</div>${c.repairAction?`<button class="btn secondary repair-action" data-repair="${esc(c.repairAction)}">Réparer</button>`:""}</article>`).join("");}
function renderDiagnostics(){const d=state.diagnostics;if(!d)return;el("diagnosticsResult").innerHTML=d.checks.map(c=>`<div class="diagnostic-card ${c.neutral?"neutral":c.ok?"ok":"bad"}"><span class="diagnostic-icon"></span><div><div class="diagnostic-label">${esc(c.label)}</div><div class="diagnostic-detail">${esc(c.detail)}</div>${c.repair?`<div class="diagnostic-repair">${esc(c.repair)}</div>`:""}</div></div>`).join("");}

function renderAssistant(compact=false){const a=state.assistant;if(!a)return;const html=a.findings.map(f=>`<div class="assistant-finding ${esc(f.severity)}"><div><strong>${esc(f.title)}</strong><div class="muted">${esc(f.summary)}</div></div>${f.action?`<button class="btn secondary assistant-action" data-assistant-action="${esc(f.action)}">Agir</button>`:""}</div>`).join("");if(compact)el("dashboardAssistant").innerHTML=html.split("</div>").slice(0,8).join("</div>");else el("assistantFindings").innerHTML=html;}

function openRoadmapModal(item){el("modalRoadmapId").textContent=item.id;el("modalRoadmapTitle").textContent=item.summary||item.title;el("modalRoadmapSummary").textContent=`Cette carte présente une formulation simplifiée en français. Les détails ci-dessous reprennent les informations techniques détectées dans le document de roadmap.`;el("modalRoadmapMeta").innerHTML=[info("Statut",roadmapLabels[item.status]||item.status),info("Titre technique",item.details?.originalTitle||item.title),info("Section",item.section||"—"),info("Ligne source",item.line||"—")].join("");el("modalRoadmapSource").textContent=item.details?.sourceExcerpt||"Aucun extrait disponible.";el("roadmapModal").classList.remove("hidden");}
function renderRoadmap(){const r=state.roadmap;if(!r?.available){el("roadmapList").innerHTML=`<div class="notice">${esc(r?.error||"Roadmap indisponible")}</div>`;return;}const s=r.summary;el("roadmapSummary").innerHTML=[["Terminés",s.done||0],["En cours",s.current||0],["À venir",s.planned||0],["Bloqués",s.blocked||0]].map(([l,v])=>`<article class="metric"><div class="metric-label">${l}</div><div class="metric-value">${v}</div><div class="metric-foot">sur ${s.total} étapes</div></article>`).join("");el("roadmapCurrent").innerHTML=r.current?`<div class="roadmap-focus"><div class="roadmap-focus-label">POSITION ACTUELLE</div><div class="roadmap-focus-id">${esc(r.current.id)}</div><div class="roadmap-focus-title">${esc(r.current.summary)}</div><div class="muted">Titre technique : ${esc(r.current.title)}</div></div>`:"";el("roadmapList").innerHTML=r.groups.map(g=>`<article class="roadmap-column ${g.status}"><div class="roadmap-column-head"><div><div class="roadmap-column-id">${esc(g.id)}</div><div class="roadmap-column-title">${esc(g.summaryTitle||g.title)}</div></div><div class="roadmap-column-percent">${g.progress}%</div></div><div class="roadmap-column-progress"><span style="width:${g.progress}%"></span></div><div class="roadmap-column-meta">${g.summary.done||0}/${g.summary.total||0} lot(s) terminés</div><div class="roadmap-column-cards">${g.items.map(i=>`<button class="roadmap-card ${i.status}" data-roadmap-id="${esc(i.id)}"><div class="roadmap-card-top"><span>${esc(i.id)}</span><span class="roadmap-badge ${i.status}">${roadmapLabels[i.status]}</span></div><div class="roadmap-card-title">${esc(i.summary)}</div><div class="roadmap-card-tech">${esc(i.title)}</div></button>`).join("")}</div></article>`).join("");}

function renderTaskResult(kind,id){const r=state.tasks?.lastResults?.[kind],host=el(id);if(!r){host.innerHTML='<div class="muted">Aucun test enregistré.</div>';return;}host.innerHTML=`<div class="result-main ${r.ok?"good":"bad"}">${r.ok?"SUCCÈS":"ÉCHEC"}</div><div class="result-meta">${r.summary?.tests!=null?`${r.summary.tests} tests · ${r.summary.passed} passés · `:""}${fmtDuration(r.durationMs)} · ${fmtDate(r.at)}</div>`;}
function renderQuality(){renderTaskResult("backendTests","backendTestResult");renderTaskResult("frontendTests","frontendTestResult");el("qualityHistory").innerHTML=(state.tasks?.history||[]).slice(0,30).map(r=>`<div class="quality-row"><span>${fmtDate(r.at)}</span><strong>${esc(r.kind)}</strong><span class="${r.ok?"good":"bad"}">${r.ok?"OK":"FAIL"}</span><span>${r.summary?.tests!=null?`${r.summary.tests} tests`:"—"}</span><span>${fmtDuration(r.durationMs)}</span></div>`).join("")||'<div class="muted">Aucun historique qualité.</div>';}

function renderDatabase(){const d=state.database;if(!d)return;const db=d.database||{};el("databasePanel").innerHTML=[info("Base",db.database||"—"),info("Utilisateur",db.user||"—"),info("Taille",db.size||"—"),info("Flyway",db.flyway?`V${db.flyway.version} · ${db.flyway.description}`:"—")].join("");el("backupList").innerHTML=(d.backups||[]).map(b=>`<div class="backup-row"><div><strong>${esc(b.name)}</strong><div class="muted">${fmtDate(b.modifiedAt)} · ${fmtBytes(b.sizeBytes)}</div></div><div class="top-actions"><button class="btn secondary restore-backup" data-file="${esc(b.file)}">Restaurer</button><button class="btn danger delete-backup" data-file="${esc(b.file)}">Supprimer</button></div></div>`).join("")||'<div class="muted">Aucun snapshot.</div>';el("migrationList").innerHTML=(d.migrations?.rows||[]).map(m=>`<div class="migration-row"><span>V${esc(m.version||"—")}</span><strong>${esc(m.description)}</strong><span>${esc(m.type)}</span><span class="${m.success?"good":"bad"}">${m.success?"OK":"FAIL"}</span><span>${fmtDate(m.installedOn)}</span></div>`).join("")||'<div class="muted">Historique Flyway indisponible.</div>';}

function renderGit(){const g=state.git;if(!g)return;el("gitSummary").innerHTML=g.available?[info("Branche",g.branch),info("Commit",g.commit),info("État",g.dirty?`${g.changedFiles} modification(s)`:"Working tree propre",g.dirty?"warn":"good"),info("Synchronisation",`Ahead ${g.ahead} · Behind ${g.behind}`,g.behind?"warn":"good"),info("Dernier commit",g.message),info("Remote",g.remote)].join(""):info("Git",g.error||"Indisponible","bad");el("gitChanges").innerHTML=g.available&&g.changes.length?g.changes.map(c=>`<div class="git-change"><span>${esc(c.status||"M")}</span><code>${esc(c.file)}</code></div>`).join(""):'<div class="muted">Aucune modification locale.</div>';}
function renderStorage(){const s=state.storage;if(!s)return;el("storageDrive").innerHTML=`<div class="storage-hero"><strong>${esc(s.drive.root)}</strong><span>${fmtBytes(s.drive.freeBytes)} libres</span></div>`;el("storageItems").innerHTML=s.items.map(i=>`<div class="storage-item"><div><strong>${esc(i.label)}</strong><div class="muted">${esc(i.path)}</div></div><div><strong>${i.sizeBytes==null?"—":fmtBytes(i.sizeBytes)}</strong>${i.cleanable?` <button class="btn danger storage-clean" data-storage-key="${i.key}">Nettoyer</button>`:""}</div></div>`).join("");el("dockerStorage").innerHTML=s.docker?.available?`<div class="notice">Docker : ${(s.docker.lines||[]).map(x=>esc(x.Type?`${x.Type} ${x.Size||""}`:x.raw||"")).join(" · ")}</div>`:"";}
function renderJournal(){const j=state.journal;if(!j)return;el("journalSummary").innerHTML=[["Sessions semaine",j.week.sessions],["Temps semaine",fmtDuration(j.week.totalMs)],["Erreurs",j.week.totalErrors],["Commits observés",j.week.commits.length]].map(([l,v])=>`<article class="metric"><div class="metric-label">${l}</div><div class="metric-value small-value">${esc(v)}</div></article>`).join("");el("journalSessions").innerHTML=j.sessions.map(s=>`<div class="journal-row"><div><strong>${fmtDate(s.startedAt)}</strong><div class="muted">${esc(s.roadmap?.id||"")} ${esc(s.roadmap?.summary||"")}</div></div><span>${fmtDuration(s.durationMs)}</span><span>${esc(s.endingGit?.branch||s.git?.branch||"—")}</span><span>${s.errors||0} erreur(s)</span></div>`).join("")||'<div class="muted">Aucune session enregistrée.</div>';}

function logLine(x){return`[${fmtTime(x.at)}] [${String(x.service).toUpperCase()}] [${x.level==="error"?"ERR":"INF"}] ${x.message}`;}function renderLogs(){el("liveConsole").textContent=state.logs.all.slice(-100).map(logLine).join("\n")||"Aucune sortie.";el("fullConsole").textContent=(state.logs[state.logFilter]||[]).map(logLine).join("\n")||"Aucune sortie.";}
function renderUpdates(){const u=state.update;if(!u)return;el("launcherVersion").textContent=`Launcher v${u.currentVersion}`;el("updateStatus").innerHTML=`<div class="update-title">${u.status==="up-to-date"?"À jour":esc(u.status)}</div><div class="update-detail">Version installée ${esc(u.currentVersion)}${u.availableVersion?` · disponible ${esc(u.availableVersion)}`:""}</div>`;el("updateProgress").style.width=`${Math.min(100,Math.max(0,u.progress?.percent||0))}%`;el("releaseHistory").innerHTML=(u.catalogue||[]).map(r=>`<article class="release-card"><div class="release-head"><div><strong>v${esc(r.version)}</strong><div class="release-title">${esc(r.title)}</div></div><span>${esc(r.status)}</span></div><ul>${(r.lots||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></article>`).join("");renderGate();}
function hydrateSettings(){const c=state.config;if(!c)return;el("cfgWorkspace").value=c.workspace||"";el("cfgPostgresPort").value=c.services?.postgres?.port||5432;el("cfgBackendPort").value=c.services?.backend?.port||8080;el("cfgFrontendPort").value=c.services?.frontend?.port||4200;el("cfgApplicationUrl").value=c.urls?.application||"";el("cfgPgadminUrl").value=c.urls?.pgadmin||"";el("cfgNotifications").checked=c.notifications?.enabled!==false;el("cfgLaunchAtLogin").checked=Boolean(c.windows?.launchAtLogin);el("cfgAutoStartDocker").checked=c.docker?.autoStart!==false;el("cfgStopDocker").checked=Boolean(c.docker?.stopWithMenPilot);renderProfiles();}

async function refreshCore(){state.snapshot=await window.men.snapshot();state.health=await window.men.health();state.git=await window.men.git();state.tasks=await window.men.taskSnapshot();state.roadmap=await window.men.roadmap();state.session=await window.men.sessionSnapshot();state.assistant=await window.men.assistant();renderDashboard();renderHealth();renderGit();renderQuality();renderRoadmap();renderSession();renderAssistant(false);}
async function refreshDatabase(){state.database=await window.men.databaseCenter();renderDatabase();}async function refreshStorage(){state.storage=await window.men.storage();renderStorage();}async function refreshJournal(){state.journal=await window.men.journal();renderJournal();}async function loadLogs(){for(const k of Object.keys(state.logs))state.logs[k]=await window.men.getLogs(k);renderLogs();}
async function serviceAction(b){busy(b,true);try{const n=b.dataset.service,a=b.dataset.action;let r;if(a==="start")r=await window.men.startService(n);if(a==="stop")r=await window.men.stopService(n);if(a==="restart")r=await window.men.restartService(n);toast(r?.ok?"Opération terminée":r?.error||"Échec",r?.ok?"success":"error");}finally{busy(b,false);await refreshCore();}}

function bind(){document.addEventListener("click",async e=>{const nav=e.target.closest(".nav-item");if(nav){document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));nav.classList.add("active");el(`section-${nav.dataset.section}`).classList.add("active");el("pageTitle").textContent=nav.textContent;if(nav.dataset.section==="database")await refreshDatabase();if(nav.dataset.section==="storage")await refreshStorage();if(nav.dataset.section==="journal")await refreshJournal();}const sa=e.target.closest(".service-action");if(sa)await serviceAction(sa);const repair=e.target.closest(".repair-action");if(repair){const r=await window.men.healthRepair(repair.dataset.repair);toast(r?.ok?"Réparation effectuée":r?.error||"Réparation impossible",r?.ok?"success":"error");await refreshCore();}const aa=e.target.closest(".assistant-action");if(aa){const action=aa.dataset.assistantAction;if(action==="open-roadmap"){document.querySelector('[data-section="roadmap"]').click();}else{const r=await window.men.healthRepair(action);toast(r?.ok?"Action effectuée":r?.error||"Action impossible",r?.ok?"success":"error");await refreshCore();}}const rc=e.target.closest(".roadmap-card");if(rc){const item=state.roadmap?.items?.find(x=>x.id===rc.dataset.roadmapId);if(item)openRoadmapModal(item);}const tb=e.target.closest(".task-button");if(tb){busy(tb,true,"Exécution...");try{const r=await window.men.runTask(tb.dataset.task);toast(r.ok?"Tâche terminée":"Tâche en échec",r.ok?"success":"error");state.tasks=await window.men.taskSnapshot();renderQuality();}finally{busy(tb,false);}}const rb=e.target.closest(".restore-backup");if(rb&&confirm("Restaurer ce snapshot ? Un snapshot de sécurité sera créé avant la restauration.")){const r=await window.men.databaseRestore(rb.dataset.file);toast(r.ok?"Snapshot restauré":r.error,r.ok?"success":"error");await refreshDatabase();}const db=e.target.closest(".delete-backup");if(db&&confirm("Supprimer définitivement ce snapshot ?")){const r=await window.men.databaseDeleteBackup(db.dataset.file);toast(r.ok?"Snapshot supprimé":r.error,r.ok?"success":"error");await refreshDatabase();}const sc=e.target.closest(".storage-clean");if(sc&&confirm("Supprimer ce cache/dossier généré ?")){const r=await window.men.storageClean(sc.dataset.storageKey);toast(r.ok?"Nettoyage terminé":r.error,r.ok?"success":"error");await refreshStorage();}});
  el("startAll").onclick=async()=>{const r=await window.men.startAll();toast(r.ok?"MEN Pilot démarré":"Démarrage incomplet",r.ok?"success":"error");await refreshCore();};el("stopAll").onclick=async()=>{const r=await window.men.stopAll();toast(r.ok?"MEN Pilot arrêté":"Arrêt incomplet",r.ok?"success":"warning");await refreshCore();};el("openApp").onclick=()=>window.men.openApplication();el("openWorkspace").onclick=()=>window.men.openWorkspace();el("openLogsFolder").onclick=()=>window.men.openLogDirectory();el("openRoadmap").onclick=()=>window.men.openRoadmapFile();el("refreshRoadmap").onclick=async()=>{state.roadmap=await window.men.roadmap();renderRoadmap();};el("refreshHealth").onclick=async()=>{state.health=await window.men.health();renderHealth();renderDashboard();};el("runDiagnostics").onclick=async()=>{state.diagnostics=await window.men.diagnostics();renderDiagnostics();};el("repairEnvironment").onclick=async()=>{const r=await window.men.repairEnvironment();state.diagnostics=r.diagnostics;renderDiagnostics();toast(r.result.ok?"Environnement réparé":"Réparation partielle",r.result.ok?"success":"warning");};el("refreshAssistant").onclick=el("refreshAssistantFull").onclick=async()=>{state.assistant=await window.men.assistant();renderAssistant(false);renderAssistant(true);};el("sessionToggle").onclick=async()=>{state.session=state.session.active?await window.men.sessionStop():await window.men.sessionStart();renderSession();};el("createBackup").onclick=async()=>{const b=el("createBackup");busy(b,true,"Sauvegarde...");const r=await window.men.databaseBackup();busy(b,false);toast(r.ok?"Snapshot créé":r.error,r.ok?"success":"error");await refreshDatabase();};el("openBackupDir").onclick=()=>window.men.openBackupDir();el("refreshDatabase").onclick=refreshDatabase;el("openGitHub").onclick=()=>window.men.openGitHub();el("gitFetch").onclick=async()=>{const r=await window.men.gitFetch();toast(r.ok?"Fetch terminé":"Fetch échoué",r.ok?"success":"error");state.git=await window.men.git();renderGit();};el("gitPull").onclick=async()=>{const r=await window.men.gitPull();toast(r.ok?"Pull terminé":r.error||"Pull échoué",r.ok?"success":"error");state.git=await window.men.git();renderGit();};el("refreshStorage").onclick=refreshStorage;el("refreshJournal").onclick=refreshJournal;el("checkUpdate").onclick=async()=>{state.update=await window.men.updateCheck();renderUpdates();};el("gateRetry").onclick=async()=>{state.update=await window.men.updateCheck();renderUpdates();};el("closeRoadmapModal").onclick=()=>el("roadmapModal").classList.add("hidden");el("roadmapModal").onclick=e=>{if(e.target===el("roadmapModal"))el("roadmapModal").classList.add("hidden");};el("profileSelect").onchange=async e=>{const r=await window.men.setProfile(e.target.value);if(!r.ok)toast(r.error,"warning");else{state.config.activeProfile=e.target.value;await refreshCore();}};
  el("logFilter").onclick=async e=>{const b=e.target.closest("button[data-service]");if(!b)return;el("logFilter").querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.logFilter=b.dataset.service;renderLogs();};
  el("settingsForm").onsubmit=async e=>{e.preventDefault();const c=structuredClone(state.config);c.workspace=el("cfgWorkspace").value.trim();c.services.postgres.port=Number(el("cfgPostgresPort").value);c.services.backend.port=Number(el("cfgBackendPort").value);c.services.frontend.port=Number(el("cfgFrontendPort").value);c.urls.application=el("cfgApplicationUrl").value.trim();c.urls.pgadmin=el("cfgPgadminUrl").value.trim();c.notifications.enabled=el("cfgNotifications").checked;c.windows.launchAtLogin=el("cfgLaunchAtLogin").checked;c.docker.autoStart=el("cfgAutoStartDocker").checked;c.docker.stopWithMenPilot=el("cfgStopDocker").checked;state.config=await window.men.saveConfig(c);toast("Configuration enregistrée","success");hydrateSettings();};
}

window.men.onUpdate(u=>{state.update=u;renderUpdates();if(u.gate==="open"&&!state.operationalLoaded)loadOperational();});window.men.onState(s=>{state.snapshot=s;renderDashboard();});window.men.onTask(t=>{state.tasks=t;renderQuality();renderDashboard();});window.men.onSession(s=>{state.session=s;renderSession();});window.men.onLog(x=>{state.logs.all.push(x);(state.logs[x.service]??=[]).push(x);renderLogs();});
async function loadOperational(){if(state.operationalLoaded)return;state.operationalLoaded=true;state.config=await window.men.getConfig();hydrateSettings();await Promise.all([refreshCore(),refreshDatabase(),loadLogs()]);setInterval(()=>refreshCore().catch(()=>{}),15000);}
(async()=>{bind();state.config=await window.men.getConfig();hydrateSettings();state.update=await window.men.updateSnapshot();renderUpdates();if(state.update?.gate==="open")await loadOperational();})();
