(()=>{
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  const date=v=>v?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
  const bytes=n=>{n=Number(n||0);if(!n)return"0 Mo";if(n>1024**3)return`${(n/1024**3).toFixed(1)} Go`;return`${(n/1024**2).toFixed(0)} Mo`;};
  function notify(message,type="success"){if(typeof toast==="function")return toast(message,type);console.log(message);}

  const nav=document.querySelector(".sidebar nav");
  if(!nav||!window.pilotage)return;
  const button=document.createElement("button");button.className="nav-item";button.dataset.section="pilotage";button.textContent="Pilotage & sécurité";nav.insertBefore(button,nav.querySelector('[data-section="logs"]'));
  const main=document.querySelector("main");const section=document.createElement("section");section.id="section-pilotage";section.className="section";
  section.innerHTML=`<div class="pilotage-grid">
    <article class="pilotage-card pilotage-wide"><div class="panel-header"><div><h2>Télémétrie & incidents</h2><div class="muted">CPU, mémoire, disponibilité des services et incidents sur la dernière heure.</div></div><div class="top-actions"><button id="pTelemetry1h" class="btn secondary">1 heure</button><button id="pTelemetry24h" class="btn secondary">24 heures</button><button id="pTelemetryRefresh" class="btn primary">Actualiser</button></div></div><div id="pTelemetryKpis" class="telemetry-kpis"></div><div id="pTelemetryChart" class="telemetry-chart"></div><div id="pIncidents" class="incident-list"></div></article>
    <article class="pilotage-card"><h2>Rapport de diagnostic</h2><div class="pilotage-note">Crée un ZIP portable contenant santé, environnement, services, Git, roadmap, qualité, base et logs récents. Les secrets détectables sont masqués.</div><div id="pReportResult"></div><div class="pilotage-actions"><button id="pCreateReport" class="btn primary">Créer le rapport</button></div></article>
    <article class="pilotage-card"><h2>Points de restauration</h2><div class="pilotage-note">Associe un commit Git, un snapshot PostgreSQL et la configuration du launcher. Une restauration crée d'abord son propre point de sécurité.</div><input id="pRestoreLabel" class="pilotage-label" placeholder="Ex. Avant T3.5 — refonte des coûts"><div class="pilotage-actions"><button id="pCreateRestore" class="btn primary">Créer un point</button></div><div id="pRestoreList" class="restore-list"></div></article>
    <article class="pilotage-card"><div class="panel-header"><div><h2>Prêt à livrer ?</h2><div class="muted">Contrôle santé, Git, tests, builds, Flyway, snapshot DB et roadmap.</div></div><button id="pReadinessRefresh" class="btn primary">Contrôler</button></div><div id="pReadiness"></div></article>
    <article class="pilotage-card"><h2>Passerelle Claude</h2><div class="pilotage-note">Prépare automatiquement le contexte de travail actuel : ROADMAP, CURRENT_STATE, CURRENT_TASK, architecture, diff Git, qualité, santé et logs utiles.</div><div id="pClaudeResult"></div><div class="pilotage-actions"><button id="pCreateClaude" class="btn primary">Préparer le contexte Claude</button></div></article>
  </div>`;
  main.appendChild(section);

  button.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(n=>n.classList.remove("active"));document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));button.classList.add("active");section.classList.add("active");const title=$("pageTitle");if(title)title.textContent="Pilotage & sécurité";refreshAll();});

  function spark(samples){if(!samples?.length)return'<div class="muted" style="padding:20px">Aucune donnée télémétrique enregistrée.</div>';const vals=samples.map(x=>Number(x.cpu||0));const max=Math.max(100,...vals),w=1000,h=150;const pts=vals.map((v,i)=>`${(i/(Math.max(1,vals.length-1)))*w},${h-(v/max)*(h-14)-7}`).join(" ");const area=`0,${h} ${pts} ${w},${h}`;return`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polygon class="telemetry-area" points="${area}"></polygon><polyline class="telemetry-line" points="${pts}"></polyline></svg>`;}
  function renderTelemetry(t){const l=t.latest||{};$("pTelemetryKpis").innerHTML=`<div class="telemetry-kpi"><span>CPU système</span><strong>${l.cpu==null?"—":`${l.cpu.toFixed(1)} %`}</strong></div><div class="telemetry-kpi"><span>Mémoire</span><strong>${l.memoryTotal?`${Math.round(l.memoryUsed/l.memoryTotal*100)} %`:"—"}</strong></div><div class="telemetry-kpi"><span>Incidents ouverts</span><strong>${t.openIncidents?.length||0}</strong></div><div class="telemetry-kpi"><span>État global</span><strong>${esc((l.health||"—").toUpperCase())}</strong></div>`;$("pTelemetryChart").innerHTML=spark(t.samples);$("pIncidents").innerHTML=(t.incidents||[]).slice(0,10).map(i=>`<div class="pilotage-row ${i.state==="open"?"incident-open":"incident-resolved"}"><div><strong>${esc(i.title)}</strong><div class="meta">${esc(i.detail||"")} · ouvert ${date(i.openedAt)}${i.closedAt?` · résolu ${date(i.closedAt)}`:""}</div></div><span>${i.state==="open"?"OUVERT":"RÉSOLU"}</span></div>`).join("")||'<div class="muted">Aucun incident enregistré.</div>';}
  async function loadTelemetry(hours=1){const t=await window.pilotage.telemetry(hours);renderTelemetry(t);}
  async function loadRestore(){const rows=await window.pilotage.restorePoints();$("pRestoreList").innerHTML=rows.slice(0,8).map(r=>`<div class="pilotage-row"><div><strong>${esc(r.label)}</strong><div class="meta">${date(r.createdAt)} · ${esc(r.git?.branch||"")} @ ${esc(r.git?.commit||"")}</div></div><button class="btn danger pRestoreRun" data-id="${esc(r.id)}">Restaurer</button></div>`).join("")||'<div class="muted">Aucun point de restauration.</div>';}
  async function loadReadiness(){const r=await window.pilotage.readiness();$("pReadiness").innerHTML=`<div class="pilotage-score"><strong class="${r.ready?"ready":"blocked"}">${r.score}%</strong><span>${r.ready?"PRÊT À LIVRER":"NON PRÊT"}</span></div><div class="readiness-grid">${r.checks.map(c=>`<div class="pilotage-row"><div><span class="pilotage-dot ${c.ok?"ok":"bad"}"></span><strong>${esc(c.label)}</strong><div class="meta">${esc(c.detail||"")}</div></div><span>${c.ok?"OK":"BLOQUANT"}</span></div>`).join("")}</div>`;}
  async function refreshAll(){await Promise.all([loadTelemetry(1),loadRestore(),loadReadiness()]);}

  $("pTelemetryRefresh").onclick=()=>loadTelemetry(1);$("pTelemetry1h").onclick=()=>loadTelemetry(1);$("pTelemetry24h").onclick=()=>loadTelemetry(24);$("pReadinessRefresh").onclick=loadReadiness;
  $("pCreateReport").onclick=async e=>{e.currentTarget.disabled=true;try{const r=await window.pilotage.createDiagnosticReport();if(r.ok){$("pReportResult").innerHTML=`<div class="pilotage-file">${esc(r.file)}</div><button class="btn secondary pReveal" data-file="${esc(r.file)}">Afficher le fichier</button>`;notify("Rapport de diagnostic créé.");}else notify(r.error||"Échec du rapport","error");}finally{e.currentTarget.disabled=false;}};
  $("pCreateRestore").onclick=async e=>{e.currentTarget.disabled=true;try{const r=await window.pilotage.createRestorePoint($("pRestoreLabel").value.trim());if(r.ok){notify("Point de restauration créé.");$("pRestoreLabel").value="";await loadRestore();}else notify(r.error||"Échec","error");}finally{e.currentTarget.disabled=false;}};
  $("pCreateClaude").onclick=async e=>{e.currentTarget.disabled=true;try{const r=await window.pilotage.createClaudeContext();if(r.ok){$("pClaudeResult").innerHTML=`<div class="pilotage-file">${esc(r.file)}</div><div class="pilotage-note">${r.current?`Contexte centré sur ${esc(r.current.id)} — ${esc(r.current.summary)}`:"Étape roadmap non détectée"}</div><button class="btn secondary pReveal" data-file="${esc(r.file)}">Afficher le pack</button>`;notify("Pack Claude prêt.");}else notify(r.error||"Échec","error");}finally{e.currentTarget.disabled=false;}};
  section.addEventListener("click",async e=>{const reveal=e.target.closest(".pReveal");if(reveal)await window.pilotage.revealFile(reveal.dataset.file);const restore=e.target.closest(".pRestoreRun");if(restore){if(!confirm("Restaurer ce point ? Le launcher créera d'abord un point de sécurité. Les modifications Git locales doivent être propres."))return;restore.disabled=true;const r=await window.pilotage.restorePoint(restore.dataset.id);notify(r.ok?"Point restauré. Git est placé sur le commit sauvegardé et la base a été restaurée.":(r.error||"Restauration échouée"),r.ok?"success":"error");restore.disabled=false;await loadRestore();}});
})();
